### ISSUE TITLE
Django 2.x compatibility

### ISSUE THREAD

**Issue by ad-m** [brack3t/django-braces#233]
Hello there,

It fails on Django 2.x 

```
Traceback (most recent call last):
  File "/home/adas/Devel/watchdog_id/watchdog_id/auth_factories/totp/tests/test_views.py", line 29, in test_get_context_data
    response = self.client.get(self.url)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/test/client.py", line 517, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/test/client.py", line 332, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/test/client.py", line 404, in generic
    return self.request(**r)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/test/client.py", line 485, in request
    raise exc_value
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/adas/Devel/watchdog_id/watchdog_id/auth_factories/totp/views.py", line 36, in dispatch
    return super(OTPPasswordCreateView, self).dispatch(request, *args, **kwargs)
  File "/home/adas/Devel/watchdog_id/watchdog_id/auth_factories/mixins.py", line 17, in dispatch
    return super(UserSessionManageMixin, self).dispatch(request, *args, **kwargs)
  File "/home/adas/.virtualenvs/watchdog_id/lib/python3.5/site-packages/braces/views/_access.py", line 98, in dispatch
    if not request.user.is_authenticated():
TypeError: 'bool' object is not callable
```

Django-braces version: 1.11.0

**Comment by tungd** [comment]
This is already fixed in the repo. You can install from git instead of PyPI.

**Comment by PetrDlouhy** [comment]
@kennethlove Is there anything, that blocks merging that branch and releasing PyPI package compatible with Django 2.0?

**Comment by kennethlove** [comment]
@PetrDlouhy there are some issues with backwards compatibility (the same code base needs to run across a bunch of different version of Django and Python) but other than that, no. If you want to get the tests all passing, I'll happily merge a PR and do a release.

**Comment by PetrDlouhy** [comment]
@kennethlove The branch `2.0` tests runs in all tested Django/Python versions. I have added Django 2.0 to the test mix and included a small test fix in #237.
Are those backwards compatibility issues not covered by the tests?

**Comment by elcolie** [comment]
Hi
django-braces==1.4.0
Is this fix in the `pull request`?

```bash
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/braces/views/__init__.py", line 19, in <module>
    from ._forms import (
  File "/Users/sarit/.pyenv/versions/poink/lib/python3.6/site-packages/braces/views/_forms.py", line 5, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

**Comment by tungd** [comment]
@elcolie it isn't. You'd need to upgrade to 1.12.0 (latest)
