### ISSUE TITLE
Cannot install from source

### ISSUE THREAD

**Issue by pasqui23** [brack3t/django-braces#261]
```
pip install --no-binary :all: django-braces              
Collecting django-braces
  Downloading https://files.pythonhosted.org/packages/e5/c3/4e3c4296ce085ad570278aa8cc4b7958553bff9ef8f1f2abb93ebd303cbe/django-braces-1.14.0.tar.gz (48kB)
     |████████████████████████████████| 51kB 222kB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /nix/store/r9zas1x2nv9bn505hq6323171f5ik5ad-python3-3.8.1/bin/python3.8 /nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gokmmxjl/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.6' wheel
       cwd: None
  Complete output (13 lines):
  Collecting setuptools>=40.6.6
    Downloading https://files.pythonhosted.org/packages/fd/76/3c7f726ed5c582019937f178d7478ce62716b7e8263344f1684cbe11ab3e/setuptools-45.0.0.zip (859kB)
  Collecting wheel
    Downloading https://files.pythonhosted.org/packages/59/b0/11710a598e1e148fb7cbf9220fd2a0b82c98e94efbdecb299cb25e7f0b39/wheel-0.33.6.tar.gz (48kB)
      ERROR: Command errored out with exit status 1:
       command: /nix/store/r9zas1x2nv9bn505hq6323171f5ik5ad-python3-3.8.1/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fetqqlr6/wheel/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fetqqlr6/wheel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fetqqlr6/wheel/pip-egg-info
           cwd: /tmp/pip-install-fetqqlr6/wheel/
      Complete output (3 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'setuptools'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /nix/store/r9zas1x2nv9bn505hq6323171f5ik5ad-python3-3.8.1/bin/python3.8 /nix/store/ksi1hlac8dfl27lviwzbbyzk2ibjirzc-python3.8-pip-19.3.1/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gokmmxjl/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.6' wheel Check the logs for full command output.
```

**Comment by SimonPe** [comment]
I have a slightly different error when trying to install from source:
```
simon@R2D2 /tmp % venv/bin/pip install --no-binary ':all:' django-braces==1.14.0
Collecting django-braces==1.14.0
  Downloading django-braces-1.14.0.tar.gz (48 kB)
     |████████████████████████████████| 48 kB 1.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/venv/bin/python3 /tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp4r7tup2d
       cwd: /tmp/pip-install-cnrf815f/django-braces
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ykkhavg0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-ykkhavg0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ykkhavg0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      import braces
  ModuleNotFoundError: No module named 'braces'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/venv/bin/python3 /tmp/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp4r7tup2d Check the logs for full command output.
```

**Comment by victor-yunenko** [comment]
I'm facing the same error. In my case django-braces is a dependency of another package, hence I resolved it by adding `django-braces < 14` to my requirements.txt.
